// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// window_intersect
NumericVector window_intersect(NumericVector a, NumericVector b);
RcppExport SEXP dhstools_window_intersect(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP );
        NumericVector __result = window_intersect(a, b);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cpp_compute_occ_exp
List cpp_compute_occ_exp(NumericMatrix lambda, NumericMatrix alpha, NumericVector alpha_offset, NumericMatrix tau);
RcppExport SEXP dhstools_cpp_compute_occ_exp(SEXP lambdaSEXP, SEXP alphaSEXP, SEXP alpha_offsetSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type alpha_offset(alpha_offsetSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type tau(tauSEXP );
        List __result = cpp_compute_occ_exp(lambda, alpha, alpha_offset, tau);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
