// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// window_intersect
NumericVector window_intersect(NumericVector a, NumericVector b);
RcppExport SEXP dhstools_window_intersect(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(window_intersect(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_occ_exp
List cpp_compute_occ_exp(NumericMatrix lambda, NumericMatrix alpha, NumericVector alpha_offset, NumericMatrix tau);
RcppExport SEXP dhstools_cpp_compute_occ_exp(SEXP lambdaSEXP, SEXP alphaSEXP, SEXP alpha_offsetSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_offset(alpha_offsetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_occ_exp(lambda, alpha, alpha_offset, tau));
    return rcpp_result_gen;
END_RCPP
}
